// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api.proto

package promotion_service_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

// Validate checks the field values on LoginResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginResponseMultiError, or
// nil if none found.
func (m *LoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for AccessToken

	// no validation rules for PartnerId

	if len(errors) > 0 {
		return LoginResponseMultiError(errors)
	}

	return nil
}

// LoginResponseMultiError is an error wrapping multiple validation errors
// returned by LoginResponse.ValidateAll() if the designated constraints
// aren't met.
type LoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginResponseMultiError) AllErrors() []error { return m }

// LoginResponseValidationError is the validation error returned by
// LoginResponse.Validate if the designated constraints aren't met.
type LoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginResponseValidationError) ErrorName() string { return "LoginResponseValidationError" }

// Error satisfies the builtin error interface
func (e LoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginResponseValidationError{}

// Validate checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Event) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Event with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EventMultiError, or nil if none found.
func (m *Event) ValidateAll() error {
	return m.validate(true)
}

func (m *Event) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Image

	// no validation rules for VouchersQuantity

	// no validation rules for FromDate

	// no validation rules for ToDate

	// no validation rules for GameId

	// no validation rules for GameName

	if len(errors) > 0 {
		return EventMultiError(errors)
	}

	return nil
}

// EventMultiError is an error wrapping multiple validation errors returned by
// Event.ValidateAll() if the designated constraints aren't met.
type EventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventMultiError) AllErrors() []error { return m }

// EventValidationError is the validation error returned by Event.Validate if
// the designated constraints aren't met.
type EventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventValidationError) ErrorName() string { return "EventValidationError" }

// Error satisfies the builtin error interface
func (e EventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventValidationError{}

// Validate checks the field values on Voucher with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Voucher) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Voucher with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in VoucherMultiError, or nil if none found.
func (m *Voucher) ValidateAll() error {
	return m.validate(true)
}

func (m *Voucher) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Code

	// no validation rules for Price

	// no validation rules for Currency

	// no validation rules for Status

	// no validation rules for ExpiredAt

	if len(errors) > 0 {
		return VoucherMultiError(errors)
	}

	return nil
}

// VoucherMultiError is an error wrapping multiple validation errors returned
// by Voucher.ValidateAll() if the designated constraints aren't met.
type VoucherMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VoucherMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VoucherMultiError) AllErrors() []error { return m }

// VoucherValidationError is the validation error returned by Voucher.Validate
// if the designated constraints aren't met.
type VoucherValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VoucherValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VoucherValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VoucherValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VoucherValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VoucherValidationError) ErrorName() string { return "VoucherValidationError" }

// Error satisfies the builtin error interface
func (e VoucherValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVoucher.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VoucherValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VoucherValidationError{}

// Validate checks the field values on GetListEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListEventsRequestMultiError, or nil if none found.
func (m *GetListEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PartnerId

	// no validation rules for Name

	// no validation rules for FromDate

	// no validation rules for ToDate

	// no validation rules for CurrentPage

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetListEventsRequestMultiError(errors)
	}

	return nil
}

// GetListEventsRequestMultiError is an error wrapping multiple validation
// errors returned by GetListEventsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetListEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListEventsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListEventsRequestMultiError) AllErrors() []error { return m }

// GetListEventsRequestValidationError is the validation error returned by
// GetListEventsRequest.Validate if the designated constraints aren't met.
type GetListEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListEventsRequestValidationError) ErrorName() string {
	return "GetListEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetListEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListEventsRequestValidationError{}

// Validate checks the field values on GetListEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListEventsResponseMultiError, or nil if none found.
func (m *GetListEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetListEventsResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetListEventsResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetListEventsResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetListEventsResponseMultiError(errors)
	}

	return nil
}

// GetListEventsResponseMultiError is an error wrapping multiple validation
// errors returned by GetListEventsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetListEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListEventsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListEventsResponseMultiError) AllErrors() []error { return m }

// GetListEventsResponseValidationError is the validation error returned by
// GetListEventsResponse.Validate if the designated constraints aren't met.
type GetListEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListEventsResponseValidationError) ErrorName() string {
	return "GetListEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetListEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListEventsResponseValidationError{}

// Validate checks the field values on UpsertEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertEventRequestMultiError, or nil if none found.
func (m *UpsertEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Image

	// no validation rules for VouchersQuantity

	// no validation rules for FromDate

	// no validation rules for ToDate

	// no validation rules for GameId

	// no validation rules for PartnerId

	if len(errors) > 0 {
		return UpsertEventRequestMultiError(errors)
	}

	return nil
}

// UpsertEventRequestMultiError is an error wrapping multiple validation errors
// returned by UpsertEventRequest.ValidateAll() if the designated constraints
// aren't met.
type UpsertEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertEventRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertEventRequestMultiError) AllErrors() []error { return m }

// UpsertEventRequestValidationError is the validation error returned by
// UpsertEventRequest.Validate if the designated constraints aren't met.
type UpsertEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertEventRequestValidationError) ErrorName() string {
	return "UpsertEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertEventRequestValidationError{}

// Validate checks the field values on UpsertEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpsertEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpsertEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpsertEventResponseMultiError, or nil if none found.
func (m *UpsertEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpsertEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpsertEventResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpsertEventResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpsertEventResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpsertEventResponseMultiError(errors)
	}

	return nil
}

// UpsertEventResponseMultiError is an error wrapping multiple validation
// errors returned by UpsertEventResponse.ValidateAll() if the designated
// constraints aren't met.
type UpsertEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpsertEventResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpsertEventResponseMultiError) AllErrors() []error { return m }

// UpsertEventResponseValidationError is the validation error returned by
// UpsertEventResponse.Validate if the designated constraints aren't met.
type UpsertEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpsertEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpsertEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpsertEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpsertEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpsertEventResponseValidationError) ErrorName() string {
	return "UpsertEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpsertEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpsertEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpsertEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpsertEventResponseValidationError{}

// Validate checks the field values on GrantPointsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrantPointsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantPointsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantPointsRequestMultiError, or nil if none found.
func (m *GrantPointsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantPointsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for EventId

	// no validation rules for GameId

	// no validation rules for Points

	if len(errors) > 0 {
		return GrantPointsRequestMultiError(errors)
	}

	return nil
}

// GrantPointsRequestMultiError is an error wrapping multiple validation errors
// returned by GrantPointsRequest.ValidateAll() if the designated constraints
// aren't met.
type GrantPointsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantPointsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantPointsRequestMultiError) AllErrors() []error { return m }

// GrantPointsRequestValidationError is the validation error returned by
// GrantPointsRequest.Validate if the designated constraints aren't met.
type GrantPointsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantPointsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantPointsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantPointsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantPointsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantPointsRequestValidationError) ErrorName() string {
	return "GrantPointsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GrantPointsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantPointsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantPointsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantPointsRequestValidationError{}

// Validate checks the field values on GrantPointsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GrantPointsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GrantPointsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GrantPointsResponseMultiError, or nil if none found.
func (m *GrantPointsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GrantPointsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return GrantPointsResponseMultiError(errors)
	}

	return nil
}

// GrantPointsResponseMultiError is an error wrapping multiple validation
// errors returned by GrantPointsResponse.ValidateAll() if the designated
// constraints aren't met.
type GrantPointsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GrantPointsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GrantPointsResponseMultiError) AllErrors() []error { return m }

// GrantPointsResponseValidationError is the validation error returned by
// GrantPointsResponse.Validate if the designated constraints aren't met.
type GrantPointsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GrantPointsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GrantPointsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GrantPointsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GrantPointsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GrantPointsResponseValidationError) ErrorName() string {
	return "GrantPointsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GrantPointsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGrantPointsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GrantPointsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GrantPointsResponseValidationError{}

// Validate checks the field values on RedeemVouchersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RedeemVouchersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedeemVouchersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedeemVouchersRequestMultiError, or nil if none found.
func (m *RedeemVouchersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RedeemVouchersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for EventId

	// no validation rules for GameId

	// no validation rules for Points

	if len(errors) > 0 {
		return RedeemVouchersRequestMultiError(errors)
	}

	return nil
}

// RedeemVouchersRequestMultiError is an error wrapping multiple validation
// errors returned by RedeemVouchersRequest.ValidateAll() if the designated
// constraints aren't met.
type RedeemVouchersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedeemVouchersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedeemVouchersRequestMultiError) AllErrors() []error { return m }

// RedeemVouchersRequestValidationError is the validation error returned by
// RedeemVouchersRequest.Validate if the designated constraints aren't met.
type RedeemVouchersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedeemVouchersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedeemVouchersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedeemVouchersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedeemVouchersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedeemVouchersRequestValidationError) ErrorName() string {
	return "RedeemVouchersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RedeemVouchersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedeemVouchersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedeemVouchersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedeemVouchersRequestValidationError{}

// Validate checks the field values on RedeemVouchersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RedeemVouchersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedeemVouchersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedeemVouchersResponseMultiError, or nil if none found.
func (m *RedeemVouchersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RedeemVouchersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RedeemVouchersResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RedeemVouchersResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RedeemVouchersResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return RedeemVouchersResponseMultiError(errors)
	}

	return nil
}

// RedeemVouchersResponseMultiError is an error wrapping multiple validation
// errors returned by RedeemVouchersResponse.ValidateAll() if the designated
// constraints aren't met.
type RedeemVouchersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedeemVouchersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedeemVouchersResponseMultiError) AllErrors() []error { return m }

// RedeemVouchersResponseValidationError is the validation error returned by
// RedeemVouchersResponse.Validate if the designated constraints aren't met.
type RedeemVouchersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedeemVouchersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedeemVouchersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedeemVouchersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedeemVouchersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedeemVouchersResponseValidationError) ErrorName() string {
	return "RedeemVouchersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RedeemVouchersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedeemVouchersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedeemVouchersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedeemVouchersResponseValidationError{}

// Validate checks the field values on Empty with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Empty) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Empty with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EmptyMultiError, or nil if none found.
func (m *Empty) ValidateAll() error {
	return m.validate(true)
}

func (m *Empty) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return EmptyMultiError(errors)
	}

	return nil
}

// EmptyMultiError is an error wrapping multiple validation errors returned by
// Empty.ValidateAll() if the designated constraints aren't met.
type EmptyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EmptyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EmptyMultiError) AllErrors() []error { return m }

// EmptyValidationError is the validation error returned by Empty.Validate if
// the designated constraints aren't met.
type EmptyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EmptyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EmptyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EmptyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EmptyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EmptyValidationError) ErrorName() string { return "EmptyValidationError" }

// Error satisfies the builtin error interface
func (e EmptyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEmpty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EmptyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EmptyValidationError{}

// Validate checks the field values on Game with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Game) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Game with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GameMultiError, or nil if none found.
func (m *Game) ValidateAll() error {
	return m.validate(true)
}

func (m *Game) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Image

	if len(errors) > 0 {
		return GameMultiError(errors)
	}

	return nil
}

// GameMultiError is an error wrapping multiple validation errors returned by
// Game.ValidateAll() if the designated constraints aren't met.
type GameMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GameMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GameMultiError) AllErrors() []error { return m }

// GameValidationError is the validation error returned by Game.Validate if the
// designated constraints aren't met.
type GameValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GameValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GameValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GameValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GameValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GameValidationError) ErrorName() string { return "GameValidationError" }

// Error satisfies the builtin error interface
func (e GameValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGame.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GameValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GameValidationError{}

// Validate checks the field values on GetListGameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListGameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListGameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListGameResponseMultiError, or nil if none found.
func (m *GetListGameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListGameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	for idx, item := range m.GetData() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetListGameResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetListGameResponseValidationError{
						field:  fmt.Sprintf("Data[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetListGameResponseValidationError{
					field:  fmt.Sprintf("Data[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetListGameResponseMultiError(errors)
	}

	return nil
}

// GetListGameResponseMultiError is an error wrapping multiple validation
// errors returned by GetListGameResponse.ValidateAll() if the designated
// constraints aren't met.
type GetListGameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListGameResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListGameResponseMultiError) AllErrors() []error { return m }

// GetListGameResponseValidationError is the validation error returned by
// GetListGameResponse.Validate if the designated constraints aren't met.
type GetListGameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListGameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListGameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListGameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListGameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListGameResponseValidationError) ErrorName() string {
	return "GetListGameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetListGameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListGameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListGameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListGameResponseValidationError{}

// Validate checks the field values on GetListEventsResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetListEventsResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetListEventsResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetListEventsResponse_DataMultiError, or nil if none found.
func (m *GetListEventsResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *GetListEventsResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalRecords

	// no validation rules for PageSize

	// no validation rules for CurrentPage

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetListEventsResponse_DataValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetListEventsResponse_DataValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetListEventsResponse_DataValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetListEventsResponse_DataMultiError(errors)
	}

	return nil
}

// GetListEventsResponse_DataMultiError is an error wrapping multiple
// validation errors returned by GetListEventsResponse_Data.ValidateAll() if
// the designated constraints aren't met.
type GetListEventsResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetListEventsResponse_DataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetListEventsResponse_DataMultiError) AllErrors() []error { return m }

// GetListEventsResponse_DataValidationError is the validation error returned
// by GetListEventsResponse_Data.Validate if the designated constraints aren't met.
type GetListEventsResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetListEventsResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetListEventsResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetListEventsResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetListEventsResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetListEventsResponse_DataValidationError) ErrorName() string {
	return "GetListEventsResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e GetListEventsResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetListEventsResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetListEventsResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetListEventsResponse_DataValidationError{}
